[build]
  command = "npm run build --configuration production"
  publish = "dist/extension-manager-angular"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-npm-install"

  [plugins.inputs]
    install_command = "npm install --legacy-peer-deps"